version: '3'
services:

  rhomis-auth-server:
    container_name: rhomis-auth-server
    restart: unless-stopped
    image: ghcr.io/l-gorman/rhomis-authenticator:latest
    ports:
      - 3002:3002
    depends_on: 
      - rhomis-auth-db
    networks:
      - app-network

  rhomis-web-server:
    container_name: rhomis-web-server
    image: nginx:mainline-alpine
    restart: unless-stopped
    volumes:
      - web-root:/var/www/html
      - ./nginx-conf/:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    ports:
      - "80:80"
    depends_on:
      - rhomis-auth-server
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - rhomis-web-server
    #entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    command: certonly --webroot --webroot-path=/var/www/html --email user@email.com --agree-tos --no-eff-email --staging -d example.org 


  rhomis-auth-db:
    image: mongo
    container_name: rhomis-auth-db
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
    networks:
      - app-network

volumes:
  certbot-etc:
  certbot-var:
  mongodb:
  web-root:
    driver: local
    driver_opts:
      type: none
      device: /home/
      o: bind

networks:
  app-network:
    driver: bridge